# Generated by Django 5.0.9 on 2024-10-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0013_subscription_featured_subscription_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={
                "ordering": ["subscription__order", "order", "featured", "-updated"]
            },
        ),
    ]
